### ISSUE TITLE
cannot find module @iarna/rtf-to-html

### ISSUE THREAD

**Issue by pegasus1982** [iarna/rtf-to-html#8]
I used this module in electron js
platform : mac 10.14 mojave
electron version : 4.0.7
It works in the developing stage.
But once it packaged, it occurred error
'cannot find module @iarna/rtf-to-html'
I can't know the reason
Please help

**Comment by Romick2005** [comment]
Probaply you need to install it not as devDependency.

**Comment by pegasus1982** [comment]
Thank you so much.
Your way helped me

**Comment by Romick2005** [comment]
Can we close this?
